-- Street Dynasty v12.0 multiplayer schema (Supabase/Postgres)
-- Run once in the Supabase SQL editor for the project configured in index.html.
create table if not exists public.player_saves (user_id uuid primary key references auth.users(id) on delete cascade, game_state jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.player_profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default 'Player', job text default 'Unemployed', reputation int default 0, cash_band text default 'Under $1K', day int default 1, location text default 'Providence', crew text default '', updated_at timestamptz not null default now());
create table if not exists public.friendships (id bigint generated by default as identity primary key, requester_id uuid not null references auth.users(id) on delete cascade, addressee_id uuid not null references auth.users(id) on delete cascade, status text not null default 'pending', created_at timestamptz not null default now(), unique(requester_id,addressee_id));
create table if not exists public.messages (id bigint generated by default as identity primary key, sender_id uuid not null references auth.users(id) on delete cascade, recipient_id uuid not null references auth.users(id) on delete cascade, body text not null check(char_length(body)<=500), created_at timestamptz not null default now());
create table if not exists public.trades (id bigint generated by default as identity primary key, sender_id uuid not null references auth.users(id) on delete cascade, recipient_id uuid not null references auth.users(id) on delete cascade, cash_offer int not null default 0 check(cash_offer>=0), status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.crews (id bigint generated by default as identity primary key, name text not null unique, owner_id uuid not null references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.crew_members (crew_id bigint not null references public.crews(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'member', created_at timestamptz not null default now(), primary key(crew_id,user_id));
create table if not exists public.challenges (id bigint generated by default as identity primary key, challenger_id uuid not null references auth.users(id) on delete cascade, opponent_id uuid not null references auth.users(id) on delete cascade, challenge_type text not null default 'Street Challenge', challenger_roll int, challenger_power int, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.city_activity (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, display_name text not null, activity text not null check(char_length(activity)<=500), created_at timestamptz not null default now());

alter table public.player_saves enable row level security; alter table public.player_profiles enable row level security; alter table public.friendships enable row level security; alter table public.messages enable row level security; alter table public.trades enable row level security; alter table public.crews enable row level security; alter table public.crew_members enable row level security; alter table public.challenges enable row level security; alter table public.city_activity enable row level security;

drop policy if exists save_owner on public.player_saves; create policy save_owner on public.player_saves for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists profiles_read on public.player_profiles; create policy profiles_read on public.player_profiles for select to authenticated using (true);
drop policy if exists profiles_owner on public.player_profiles; create policy profiles_owner on public.player_profiles for all using (auth.uid()=id) with check (auth.uid()=id);
drop policy if exists friends_party on public.friendships; create policy friends_party on public.friendships for all using (auth.uid()=requester_id or auth.uid()=addressee_id) with check (auth.uid()=requester_id or auth.uid()=addressee_id);
drop policy if exists messages_read on public.messages; create policy messages_read on public.messages for select using (auth.uid()=sender_id or auth.uid()=recipient_id);
drop policy if exists messages_send on public.messages; create policy messages_send on public.messages for insert with check (auth.uid()=sender_id);
drop policy if exists trades_party on public.trades; create policy trades_party on public.trades for all using (auth.uid()=sender_id or auth.uid()=recipient_id) with check (auth.uid()=sender_id or auth.uid()=recipient_id);
drop policy if exists crews_read on public.crews; create policy crews_read on public.crews for select to authenticated using (true);
drop policy if exists crews_create on public.crews; create policy crews_create on public.crews for insert with check (auth.uid()=owner_id);
drop policy if exists crews_owner on public.crews; create policy crews_owner on public.crews for update using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
drop policy if exists crew_members_read on public.crew_members; create policy crew_members_read on public.crew_members for select to authenticated using (true);
drop policy if exists crew_members_self on public.crew_members; create policy crew_members_self on public.crew_members for insert with check (auth.uid()=user_id);
drop policy if exists challenges_party on public.challenges; create policy challenges_party on public.challenges for all using (auth.uid()=challenger_id or auth.uid()=opponent_id) with check (auth.uid()=challenger_id or auth.uid()=opponent_id);
drop policy if exists activity_read on public.city_activity; create policy activity_read on public.city_activity for select to authenticated using (true);
drop policy if exists activity_post on public.city_activity; create policy activity_post on public.city_activity for insert with check (auth.uid()=user_id);

-- v12.1 ONLINE DEPTH UPGRADE
alter table public.trades add column if not exists settled_at timestamptz;
alter table public.challenges add column if not exists opponent_power int;
alter table public.challenges add column if not exists winner_id uuid references auth.users(id) on delete set null;
alter table public.challenges add column if not exists resolved_at timestamptz;

create table if not exists public.player_reports (
 id bigint generated by default as identity primary key,
 reporter_id uuid not null references auth.users(id) on delete cascade,
 reported_id uuid not null references auth.users(id) on delete cascade,
 reason text not null check(char_length(reason) between 3 and 300),
 status text not null default 'open',
 created_at timestamptz not null default now()
);
create table if not exists public.player_blocks (
 blocker_id uuid not null references auth.users(id) on delete cascade,
 blocked_id uuid not null references auth.users(id) on delete cascade,
 created_at timestamptz not null default now(),
 primary key(blocker_id,blocked_id)
);
alter table public.player_reports enable row level security;
alter table public.player_blocks enable row level security;
drop policy if exists reports_insert on public.player_reports; create policy reports_insert on public.player_reports for insert with check(auth.uid()=reporter_id and reporter_id<>reported_id);
drop policy if exists reports_own on public.player_reports; create policy reports_own on public.player_reports for select using(auth.uid()=reporter_id);
drop policy if exists blocks_owner on public.player_blocks; create policy blocks_owner on public.player_blocks for all using(auth.uid()=blocker_id) with check(auth.uid()=blocker_id and blocker_id<>blocked_id);

create or replace function public.sd_accept_trade(p_trade_id bigint) returns text
language plpgsql security definer set search_path=public as $$
declare t public.trades%rowtype; sender_state jsonb; receiver_state jsonb; sender_cash int; receiver_cash int;
begin
 select * into t from public.trades where id=p_trade_id for update;
 if not found then raise exception 'Trade not found'; end if;
 if auth.uid()<>t.recipient_id then raise exception 'Only recipient can accept'; end if;
 if t.status<>'pending' then raise exception 'Trade is not pending'; end if;
 select game_state into sender_state from public.player_saves where user_id=t.sender_id for update;
 select game_state into receiver_state from public.player_saves where user_id=t.recipient_id for update;
 if sender_state is null or receiver_state is null then raise exception 'Both players must sync cloud saves first'; end if;
 sender_cash:=coalesce((sender_state->>'cash')::int,0); receiver_cash:=coalesce((receiver_state->>'cash')::int,0);
 if sender_cash<t.cash_offer then raise exception 'Sender no longer has enough cash'; end if;
 sender_state:=jsonb_set(sender_state,'{cash}',to_jsonb(sender_cash-t.cash_offer),true);
 receiver_state:=jsonb_set(receiver_state,'{cash}',to_jsonb(receiver_cash+t.cash_offer),true);
 update public.player_saves set game_state=sender_state,updated_at=now() where user_id=t.sender_id;
 update public.player_saves set game_state=receiver_state,updated_at=now() where user_id=t.recipient_id;
 update public.trades set status='accepted',settled_at=now() where id=p_trade_id;
 return 'Trade accepted: $'||t.cash_offer||' transferred';
end $$;
revoke all on function public.sd_accept_trade(bigint) from public; grant execute on function public.sd_accept_trade(bigint) to authenticated;

create or replace function public.sd_resolve_challenge(p_challenge_id bigint,p_opponent_power int) returns text
language plpgsql security definer set search_path=public as $$
declare c public.challenges%rowtype; opponent_roll int; a_score int; b_score int; w uuid;
begin
 select * into c from public.challenges where id=p_challenge_id for update;
 if not found then raise exception 'Challenge not found'; end if;
 if auth.uid()<>c.opponent_id then raise exception 'Only challenged player can resolve'; end if;
 if c.status<>'pending' then raise exception 'Challenge already resolved'; end if;
 opponent_roll:=floor(random()*100+1)::int; a_score:=coalesce(c.challenger_roll,1)+coalesce(c.challenger_power,0); b_score:=opponent_roll+greatest(0,p_opponent_power);
 w:=case when b_score>a_score then c.opponent_id else c.challenger_id end;
 update public.challenges set opponent_power=p_opponent_power,winner_id=w,status='resolved',resolved_at=now() where id=p_challenge_id;
 return case when w=auth.uid() then '🏆 You won the challenge.' else 'Challenge complete — your opponent won.' end;
end $$;
revoke all on function public.sd_resolve_challenge(bigint,int) from public; grant execute on function public.sd_resolve_challenge(bigint,int) to authenticated;
